/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {},
  },
  safelist: [
    "bg-red-500",
    "bg-green-500",
    "bg-blue-500",
    "bg-yellow-500",
    "bg-indigo-500",
    "bg-purple-500",
    "bg-pink-500",
    "bg-gray-500",
    "bg-white",
    "bg-black",
    "text-red-500",
    "text-green-500",
    "text-blue-500",
    "text-yellow-500",
    "text-indigo-500",
    "text-purple-500",
    "text-pink-500",
    "text-gray-500",
    "text-white",
    "text-black",
    "border-red-500",
    "border-green-500",
    "border-blue-500",
    "border-yellow-500",
    "border-indigo-500",
    "border-purple-500",
    "border-pink-500",
    "border-gray-500",
    "border-white",
    "border-black",
    "text-left",
    "text-center",
    "text-right",
    "text-justify",
    "font-bold",
    "font-semibold",
    "font-normal",
    "font-light",
    "font-thin",
    "font-extrabold",
    "font-black",
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
  ],
  plugins: [],
  darkMode: "selector",
};
